[versions]
kotlinVersion = "1.9.10"
androidGradleVersion = "8.1.4"
androidSdkCommonVersion = "31.1.2"

# kotlinx
kotlinxSerializationVersion = "1.6.1"
kotlinxCoroutinesVersion = "1.6.4"

# android
androidAppCompatVersion = "1.6.1"

# android compose
composeUiVersion = "1.5.1"

# jetbrains compose
composeJetbrainsVersion = "1.5.1"

# jvm
apacheCommonsTextVersion = "1.10.0"
kotlinPoetVersion = "1.13.1"
detektVersion = "1.22.0"
icu4jVersion = "73.1"
commonsCodecVersion = "1.15"
batikVersion = "1.16"

# moko
mokoGraphicsVersion = "0.9.0"
mokoTestVersion = "0.6.1"
mokoMultiplatformPluginVersion = "0.14.2"

[libraries]
# kotlinx
kotlinxSerialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationVersion" }
kotlinxCoroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutinesVersion" }

# moko
mokoGraphics = { module = "dev.icerock.moko:graphics", version.ref = "mokoGraphicsVersion" }
mokoTestCore = { module = "dev.icerock.moko:test-core", version.ref = "mokoTestVersion" }

# android
appCompat = { module = "androidx.appcompat:appcompat", version.ref = "androidAppCompatVersion" }

# android compose
composeUi = { module = "androidx.compose.ui:ui", version.ref = "composeUiVersion" }

# jvm
kotlinPoet = { module = "com.squareup:kotlinpoet", version.ref = "kotlinPoetVersion" }
apacheCommonsText = { module = "org.apache.commons:commons-text", version.ref = "apacheCommonsTextVersion" }
batikRasterizer = { module = "org.apache.xmlgraphics:batik-rasterizer", version.ref = "batikVersion" }
batikTranscoder = { module = "org.apache.xmlgraphics:batik-transcoder", version.ref = "batikVersion" }
commonsCodec = { module = "commons-codec:commons-codec", version.ref = "commonsCodecVersion" }
icu4j = { module = "com.ibm.icu:icu4j", version.ref = "icu4jVersion" }

# gradle
kotlinGradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlinVersion" }
androidGradlePlugin = { module = "com.android.tools.build:gradle", version.ref = "androidGradleVersion" }
androidSdkCommon = { module = "com.android.tools:sdk-common", version.ref = "androidSdkCommonVersion" }
kotlinCompilerEmbeddable = { module = "org.jetbrains.kotlin:kotlin-compiler-embeddable", version.ref = "kotlinVersion" }
detektGradlePlugin = { module = "io.gitlab.arturbosch.detekt:detekt-gradle-plugin", version.ref = "detektVersion" }
mokoMultiplatformPlugin = { module = "dev.icerock:mobile-multiplatform", version.ref = "mokoMultiplatformPluginVersion" }
composeJetBrainsPlugin = { module = "org.jetbrains.compose:compose-gradle-plugin", version.ref = "composeJetbrainsVersion" }
