[versions]
kotlinVersion = "1.5.21"
androidGradleVersion = "4.1.2"
androidAppCompatVersion = "1.2.0"
espressoCoreVersion = "3.3.0"
testRunnerVersion = "1.3.0"
testRulesVersion = "1.3.0"
testExtJunitVersion = "1.1.2"
testCoreVersion = "1.3.0"
robolectricVersion = "4.5.1"
apacheCommonsTextVersion = "1.3"
kotlinPoetVersion = "1.6.0"
kotlinxSerializationVersion = "1.2.1"
detektVersion = "1.15.0"
mokoGraphicsVersion = "0.7.0"
mokoParcelizeVersion = "0.7.1"
mokoResourcesVersion = "0.17.0"
composeVersion = "1.0.1"
constraintLayoutVersion = "2.0.4"
composeActivityVersion = "1.3.1"
icu4jVersion = "69.1"

[libraries]
appCompat = { module = "androidx.appcompat:appcompat", version.ref = "androidAppCompatVersion" }
espressoCore = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCoreVersion" }
kotlinTestJUnit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlinVersion" }
testCore = { module = "androidx.test:core", version.ref = "testCoreVersion" }
robolectric = { module = "org.robolectric:robolectric", version.ref = "robolectricVersion" }
testRunner = { module = "androidx.test:runner", version.ref = "testRunnerVersion" }
testRules = { module = "androidx.test:rules", version.ref = "testRulesVersion" }
testExtJunit = { module = "androidx.test.ext:junit", version.ref = "testExtJunitVersion" }
mokoResources = { module = "dev.icerock.moko:resources", version.ref = "mokoResourcesVersion" }
mokoParcelize = { module = "dev.icerock.moko:parcelize", version.ref = "mokoParcelizeVersion" }
mokoGraphics = { module = "dev.icerock.moko:graphics", version.ref = "mokoGraphicsVersion" }
kotlinTest = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlinVersion" }
kotlinTestAnnotations = { module = "org.jetbrains.kotlin:kotlin-test-annotations-common", version.ref = "kotlinVersion" }
kotlinPoet = { module = "com.squareup:kotlinpoet", version.ref = "kotlinPoetVersion" }
kotlinxSerialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationVersion" }
apacheCommonsText = { module = "org.apache.commons:commons-text", version.ref = "apacheCommonsTextVersion" }
kotlinGradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlinVersion" }
androidGradlePlugin = { module = "com.android.tools.build:gradle", version.ref = "androidGradleVersion" }
kotlinCompilerEmbeddable = { module = "org.jetbrains.kotlin:kotlin-compiler-embeddable", version.ref = "kotlinVersion" }
composeUi = { module = "androidx.compose.ui:ui", version.ref = "composeVersion" }
composeUiTooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "composeVersion" }
composeUiToolingPreview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "composeVersion" }
composeRuntime = { module = "androidx.compose.runtime:runtime", version.ref = "composeVersion" }
composeMaterial = { module = "androidx.compose.material:material", version.ref = "composeVersion" }
composeFoundation = { module = "androidx.compose.foundation:foundation", version.ref = "composeVersion" }
composeActivity = { module = "androidx.activity:activity-compose", version.ref = "composeActivityVersion" }
constraintLayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintLayoutVersion" }
icu4j = { module = "com.ibm.icu:icu4j", version.ref = "icu4jVersion" }

