[versions]
kotlinVersion = "1.6.10"
androidGradleVersion = "7.0.4"

# kotlinx
kotlinxSerializationVersion = "1.2.1"

# android
constraintLayoutVersion = "2.0.4"
androidAppCompatVersion = "1.2.0"

# android compose
composeVersion = "1.0.5"
composeActivityVersion = "1.3.1"

# jvm
apacheCommonsTextVersion = "1.3"
kotlinPoetVersion = "1.10.2"
detektVersion = "1.19.0"
icu4jVersion = "69.1"
commonsCodecVersion = "1.15"

# tests
espressoCoreVersion = "3.3.0"
testRunnerVersion = "1.3.0"
testRulesVersion = "1.3.0"
testExtJunitVersion = "1.1.2"
testCoreVersion = "1.3.0"
robolectricVersion = "4.6"

# moko
mokoGraphicsVersion = "0.9.0"
mokoParcelizeVersion = "0.8.0"
mokoTestVersion = "0.5.0"
mokoResourcesVersion = "0.18.0"

[libraries]
# kotlinx
kotlinxSerialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationVersion" }

# moko
mokoParcelize = { module = "dev.icerock.moko:parcelize", version.ref = "mokoParcelizeVersion" }
mokoGraphics = { module = "dev.icerock.moko:graphics", version.ref = "mokoGraphicsVersion" }
mokoTestCore = { module = "dev.icerock.moko:test-core", version.ref = "mokoTestVersion" }

# android
appCompat = { module = "androidx.appcompat:appcompat", version.ref = "androidAppCompatVersion" }
constraintLayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintLayoutVersion" }

# android compose
composeUi = { module = "androidx.compose.ui:ui", version.ref = "composeVersion" }
composeUiTooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "composeVersion" }
composeUiToolingPreview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "composeVersion" }
composeRuntime = { module = "androidx.compose.runtime:runtime", version.ref = "composeVersion" }
composeMaterial = { module = "androidx.compose.material:material", version.ref = "composeVersion" }
composeFoundation = { module = "androidx.compose.foundation:foundation", version.ref = "composeVersion" }
composeActivity = { module = "androidx.activity:activity-compose", version.ref = "composeActivityVersion" }

# jvm
kotlinPoet = { module = "com.squareup:kotlinpoet", version.ref = "kotlinPoetVersion" }
apacheCommonsText = { module = "org.apache.commons:commons-text", version.ref = "apacheCommonsTextVersion" }
commonsCodec = { module = "commons-codec:commons-codec", version.ref = "commonsCodecVersion" }
icu4j = { module = "com.ibm.icu:icu4j", version.ref = "icu4jVersion" }

# tests
espressoCore = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCoreVersion" }
kotlinTestJUnit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlinVersion" }
testCore = { module = "androidx.test:core", version.ref = "testCoreVersion" }
robolectric = { module = "org.robolectric:robolectric", version.ref = "robolectricVersion" }
testRunner = { module = "androidx.test:runner", version.ref = "testRunnerVersion" }
testRules = { module = "androidx.test:rules", version.ref = "testRulesVersion" }
testExtJunit = { module = "androidx.test.ext:junit", version.ref = "testExtJunitVersion" }
kotlinTest = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlinVersion" }
kotlinTestAnnotations = { module = "org.jetbrains.kotlin:kotlin-test-annotations-common", version.ref = "kotlinVersion" }

# gradle
kotlinGradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlinVersion" }
androidGradlePlugin = { module = "com.android.tools.build:gradle", version.ref = "androidGradleVersion" }
kotlinCompilerEmbeddable = { module = "org.jetbrains.kotlin:kotlin-compiler-embeddable", version.ref = "kotlinVersion" }
